// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: user.proto

package userpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core definition
type Buyer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buyer) Reset() {
	*x = Buyer{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buyer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buyer) ProtoMessage() {}

func (x *Buyer) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buyer.ProtoReflect.Descriptor instead.
func (*Buyer) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *Buyer) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Buyer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Buyer) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Buyer) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *Buyer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Buyer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Seller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	BankAccount   string                 `protobuf:"bytes,4,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	TaxCode       string                 `protobuf:"bytes,5,opt,name=tax_code,json=taxCode,proto3" json:"tax_code,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seller) Reset() {
	*x = Seller{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seller) ProtoMessage() {}

func (x *Seller) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seller.ProtoReflect.Descriptor instead.
func (*Seller) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *Seller) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Seller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seller) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Seller) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

func (x *Seller) GetTaxCode() string {
	if x != nil {
		return x.TaxCode
	}
	return ""
}

func (x *Seller) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Seller) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *Seller) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Seller) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// For Buyer gRPC
type CreateBuyerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         *Buyer                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuyerRequest) Reset() {
	*x = CreateBuyerRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyerRequest) ProtoMessage() {}

func (x *CreateBuyerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuyerRequest.ProtoReflect.Descriptor instead.
func (*CreateBuyerRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBuyerRequest) GetBuyer() *Buyer {
	if x != nil {
		return x.Buyer
	}
	return nil
}

type CreateBuyerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuyerResponse) Reset() {
	*x = CreateBuyerResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyerResponse) ProtoMessage() {}

func (x *CreateBuyerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuyerResponse.ProtoReflect.Descriptor instead.
func (*CreateBuyerResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBuyerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBuyerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateBuyerByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         *Buyer                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuyerByUserIDRequest) Reset() {
	*x = UpdateBuyerByUserIDRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuyerByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuyerByUserIDRequest) ProtoMessage() {}

func (x *UpdateBuyerByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuyerByUserIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateBuyerByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBuyerByUserIDRequest) GetBuyer() *Buyer {
	if x != nil {
		return x.Buyer
	}
	return nil
}

type UpdateBuyerByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuyerByUserIDResponse) Reset() {
	*x = UpdateBuyerByUserIDResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuyerByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuyerByUserIDResponse) ProtoMessage() {}

func (x *UpdateBuyerByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuyerByUserIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateBuyerByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBuyerByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateBuyerByUserIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetBuyerByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuyerByUserIDRequest) Reset() {
	*x = GetBuyerByUserIDRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyerByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyerByUserIDRequest) ProtoMessage() {}

func (x *GetBuyerByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuyerByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetBuyerByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetBuyerByUserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBuyerByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         *Buyer                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuyerByUserIDResponse) Reset() {
	*x = GetBuyerByUserIDResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyerByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyerByUserIDResponse) ProtoMessage() {}

func (x *GetBuyerByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuyerByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetBuyerByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetBuyerByUserIDResponse) GetBuyer() *Buyer {
	if x != nil {
		return x.Buyer
	}
	return nil
}

func (x *GetBuyerByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBuyerByUserIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DelBuyerByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelBuyerByUserIDRequest) Reset() {
	*x = DelBuyerByUserIDRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelBuyerByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelBuyerByUserIDRequest) ProtoMessage() {}

func (x *DelBuyerByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelBuyerByUserIDRequest.ProtoReflect.Descriptor instead.
func (*DelBuyerByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *DelBuyerByUserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DelBuyerByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelBuyerByUserIDResponse) Reset() {
	*x = DelBuyerByUserIDResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelBuyerByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelBuyerByUserIDResponse) ProtoMessage() {}

func (x *DelBuyerByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelBuyerByUserIDResponse.ProtoReflect.Descriptor instead.
func (*DelBuyerByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *DelBuyerByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DelBuyerByUserIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// For Seller gRPC
type CreateSellerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        *Seller                `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSellerRequest) Reset() {
	*x = CreateSellerRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellerRequest) ProtoMessage() {}

func (x *CreateSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellerRequest.ProtoReflect.Descriptor instead.
func (*CreateSellerRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSellerRequest) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type CreateSellerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSellerResponse) Reset() {
	*x = CreateSellerResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellerResponse) ProtoMessage() {}

func (x *CreateSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellerResponse.ProtoReflect.Descriptor instead.
func (*CreateSellerResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSellerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateSellerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateSellerByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        *Seller                `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSellerByUserIDRequest) Reset() {
	*x = UpdateSellerByUserIDRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSellerByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerByUserIDRequest) ProtoMessage() {}

func (x *UpdateSellerByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerByUserIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateSellerByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSellerByUserIDRequest) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type UpdateSellerByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSellerByUserIDResponse) Reset() {
	*x = UpdateSellerByUserIDResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSellerByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerByUserIDResponse) ProtoMessage() {}

func (x *UpdateSellerByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerByUserIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateSellerByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSellerByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateSellerByUserIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSellerByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerByUserIDRequest) Reset() {
	*x = GetSellerByUserIDRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerByUserIDRequest) ProtoMessage() {}

func (x *GetSellerByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetSellerByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetSellerByUserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSellerByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        *Seller                `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerByUserIDResponse) Reset() {
	*x = GetSellerByUserIDResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerByUserIDResponse) ProtoMessage() {}

func (x *GetSellerByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetSellerByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetSellerByUserIDResponse) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

func (x *GetSellerByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSellerByUserIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DelSellerByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelSellerByUserIDRequest) Reset() {
	*x = DelSellerByUserIDRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSellerByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSellerByUserIDRequest) ProtoMessage() {}

func (x *DelSellerByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSellerByUserIDRequest.ProtoReflect.Descriptor instead.
func (*DelSellerByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *DelSellerByUserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DelSellerByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelSellerByUserIDResponse) Reset() {
	*x = DelSellerByUserIDResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSellerByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSellerByUserIDResponse) ProtoMessage() {}

func (x *DelSellerByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSellerByUserIDResponse.ProtoReflect.Descriptor instead.
func (*DelSellerByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *DelSellerByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DelSellerByUserIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x13user_service.pkg.pb\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n" +
	"\x05Buyer\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12>\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"\x9d\x02\n" +
	"\x06Seller\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12!\n" +
	"\fbank_account\x18\x04 \x01(\tR\vbankAccount\x12\x19\n" +
	"\btax_code\x18\x05 \x01(\tR\ataxCode\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12>\n" +
	"\rdate_of_birth\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\"F\n" +
	"\x12CreateBuyerRequest\x120\n" +
	"\x05buyer\x18\x01 \x01(\v2\x1a.user_service.pkg.pb.BuyerR\x05buyer\"I\n" +
	"\x13CreateBuyerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"N\n" +
	"\x1aUpdateBuyerByUserIDRequest\x120\n" +
	"\x05buyer\x18\x01 \x01(\v2\x1a.user_service.pkg.pb.BuyerR\x05buyer\"Q\n" +
	"\x1bUpdateBuyerByUserIDResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"2\n" +
	"\x17GetBuyerByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x80\x01\n" +
	"\x18GetBuyerByUserIDResponse\x120\n" +
	"\x05buyer\x18\x01 \x01(\v2\x1a.user_service.pkg.pb.BuyerR\x05buyer\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"2\n" +
	"\x17DelBuyerByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"N\n" +
	"\x18DelBuyerByUserIDResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"J\n" +
	"\x13CreateSellerRequest\x123\n" +
	"\x06seller\x18\x01 \x01(\v2\x1b.user_service.pkg.pb.SellerR\x06seller\"J\n" +
	"\x14CreateSellerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"R\n" +
	"\x1bUpdateSellerByUserIDRequest\x123\n" +
	"\x06seller\x18\x01 \x01(\v2\x1b.user_service.pkg.pb.SellerR\x06seller\"R\n" +
	"\x1cUpdateSellerByUserIDResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"3\n" +
	"\x18GetSellerByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x84\x01\n" +
	"\x19GetSellerByUserIDResponse\x123\n" +
	"\x06seller\x18\x01 \x01(\v2\x1b.user_service.pkg.pb.SellerR\x06seller\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"3\n" +
	"\x18DelSellerByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"O\n" +
	"\x19DelSellerByUserIDResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x95\a\n" +
	"\vUserService\x12`\n" +
	"\vCreateBuyer\x12'.user_service.pkg.pb.CreateBuyerRequest\x1a(.user_service.pkg.pb.CreateBuyerResponse\x12x\n" +
	"\x13UpdateBuyerByUserID\x12/.user_service.pkg.pb.UpdateBuyerByUserIDRequest\x1a0.user_service.pkg.pb.UpdateBuyerByUserIDResponse\x12o\n" +
	"\x10GetBuyerByUserID\x12,.user_service.pkg.pb.GetBuyerByUserIDRequest\x1a-.user_service.pkg.pb.GetBuyerByUserIDResponse\x12o\n" +
	"\x10DelBuyerByUserID\x12,.user_service.pkg.pb.DelBuyerByUserIDRequest\x1a-.user_service.pkg.pb.DelBuyerByUserIDResponse\x12c\n" +
	"\fCreateSeller\x12(.user_service.pkg.pb.CreateSellerRequest\x1a).user_service.pkg.pb.CreateSellerResponse\x12{\n" +
	"\x14UpdateSellerByUserID\x120.user_service.pkg.pb.UpdateSellerByUserIDRequest\x1a1.user_service.pkg.pb.UpdateSellerByUserIDResponse\x12r\n" +
	"\x11GetSellerByUserID\x12-.user_service.pkg.pb.GetSellerByUserIDRequest\x1a..user_service.pkg.pb.GetSellerByUserIDResponse\x12r\n" +
	"\x11DelSellerByUserID\x12-.user_service.pkg.pb.DelSellerByUserIDRequest\x1a..user_service.pkg.pb.DelSellerByUserIDResponseB\x15Z\x13user-service/userpbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_user_proto_goTypes = []any{
	(*Buyer)(nil),                        // 0: user_service.pkg.pb.Buyer
	(*Seller)(nil),                       // 1: user_service.pkg.pb.Seller
	(*CreateBuyerRequest)(nil),           // 2: user_service.pkg.pb.CreateBuyerRequest
	(*CreateBuyerResponse)(nil),          // 3: user_service.pkg.pb.CreateBuyerResponse
	(*UpdateBuyerByUserIDRequest)(nil),   // 4: user_service.pkg.pb.UpdateBuyerByUserIDRequest
	(*UpdateBuyerByUserIDResponse)(nil),  // 5: user_service.pkg.pb.UpdateBuyerByUserIDResponse
	(*GetBuyerByUserIDRequest)(nil),      // 6: user_service.pkg.pb.GetBuyerByUserIDRequest
	(*GetBuyerByUserIDResponse)(nil),     // 7: user_service.pkg.pb.GetBuyerByUserIDResponse
	(*DelBuyerByUserIDRequest)(nil),      // 8: user_service.pkg.pb.DelBuyerByUserIDRequest
	(*DelBuyerByUserIDResponse)(nil),     // 9: user_service.pkg.pb.DelBuyerByUserIDResponse
	(*CreateSellerRequest)(nil),          // 10: user_service.pkg.pb.CreateSellerRequest
	(*CreateSellerResponse)(nil),         // 11: user_service.pkg.pb.CreateSellerResponse
	(*UpdateSellerByUserIDRequest)(nil),  // 12: user_service.pkg.pb.UpdateSellerByUserIDRequest
	(*UpdateSellerByUserIDResponse)(nil), // 13: user_service.pkg.pb.UpdateSellerByUserIDResponse
	(*GetSellerByUserIDRequest)(nil),     // 14: user_service.pkg.pb.GetSellerByUserIDRequest
	(*GetSellerByUserIDResponse)(nil),    // 15: user_service.pkg.pb.GetSellerByUserIDResponse
	(*DelSellerByUserIDRequest)(nil),     // 16: user_service.pkg.pb.DelSellerByUserIDRequest
	(*DelSellerByUserIDResponse)(nil),    // 17: user_service.pkg.pb.DelSellerByUserIDResponse
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	18, // 0: user_service.pkg.pb.Buyer.date_of_birth:type_name -> google.protobuf.Timestamp
	18, // 1: user_service.pkg.pb.Seller.date_of_birth:type_name -> google.protobuf.Timestamp
	0,  // 2: user_service.pkg.pb.CreateBuyerRequest.buyer:type_name -> user_service.pkg.pb.Buyer
	0,  // 3: user_service.pkg.pb.UpdateBuyerByUserIDRequest.buyer:type_name -> user_service.pkg.pb.Buyer
	0,  // 4: user_service.pkg.pb.GetBuyerByUserIDResponse.buyer:type_name -> user_service.pkg.pb.Buyer
	1,  // 5: user_service.pkg.pb.CreateSellerRequest.seller:type_name -> user_service.pkg.pb.Seller
	1,  // 6: user_service.pkg.pb.UpdateSellerByUserIDRequest.seller:type_name -> user_service.pkg.pb.Seller
	1,  // 7: user_service.pkg.pb.GetSellerByUserIDResponse.seller:type_name -> user_service.pkg.pb.Seller
	2,  // 8: user_service.pkg.pb.UserService.CreateBuyer:input_type -> user_service.pkg.pb.CreateBuyerRequest
	4,  // 9: user_service.pkg.pb.UserService.UpdateBuyerByUserID:input_type -> user_service.pkg.pb.UpdateBuyerByUserIDRequest
	6,  // 10: user_service.pkg.pb.UserService.GetBuyerByUserID:input_type -> user_service.pkg.pb.GetBuyerByUserIDRequest
	8,  // 11: user_service.pkg.pb.UserService.DelBuyerByUserID:input_type -> user_service.pkg.pb.DelBuyerByUserIDRequest
	10, // 12: user_service.pkg.pb.UserService.CreateSeller:input_type -> user_service.pkg.pb.CreateSellerRequest
	12, // 13: user_service.pkg.pb.UserService.UpdateSellerByUserID:input_type -> user_service.pkg.pb.UpdateSellerByUserIDRequest
	14, // 14: user_service.pkg.pb.UserService.GetSellerByUserID:input_type -> user_service.pkg.pb.GetSellerByUserIDRequest
	16, // 15: user_service.pkg.pb.UserService.DelSellerByUserID:input_type -> user_service.pkg.pb.DelSellerByUserIDRequest
	3,  // 16: user_service.pkg.pb.UserService.CreateBuyer:output_type -> user_service.pkg.pb.CreateBuyerResponse
	5,  // 17: user_service.pkg.pb.UserService.UpdateBuyerByUserID:output_type -> user_service.pkg.pb.UpdateBuyerByUserIDResponse
	7,  // 18: user_service.pkg.pb.UserService.GetBuyerByUserID:output_type -> user_service.pkg.pb.GetBuyerByUserIDResponse
	9,  // 19: user_service.pkg.pb.UserService.DelBuyerByUserID:output_type -> user_service.pkg.pb.DelBuyerByUserIDResponse
	11, // 20: user_service.pkg.pb.UserService.CreateSeller:output_type -> user_service.pkg.pb.CreateSellerResponse
	13, // 21: user_service.pkg.pb.UserService.UpdateSellerByUserID:output_type -> user_service.pkg.pb.UpdateSellerByUserIDResponse
	15, // 22: user_service.pkg.pb.UserService.GetSellerByUserID:output_type -> user_service.pkg.pb.GetSellerByUserIDResponse
	17, // 23: user_service.pkg.pb.UserService.DelSellerByUserID:output_type -> user_service.pkg.pb.DelSellerByUserIDResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
