// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: order.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_CreateOrder_FullMethodName              = "/order_service.pkg.pb.OrderService/CreateOrder"
	OrderService_GetOrderByIDWithItems_FullMethodName    = "/order_service.pkg.pb.OrderService/GetOrderByIDWithItems"
	OrderService_GetOrderByIDOnly_FullMethodName         = "/order_service.pkg.pb.OrderService/GetOrderByIDOnly"
	OrderService_GetOrdersByBuyerIDStatus_FullMethodName = "/order_service.pkg.pb.OrderService/GetOrdersByBuyerIDStatus"
	OrderService_GetOrderItemsByOrderID_FullMethodName   = "/order_service.pkg.pb.OrderService/GetOrderItemsByOrderID"
	OrderService_UpdateOrderByID_FullMethodName          = "/order_service.pkg.pb.OrderService/UpdateOrderByID"
	OrderService_CancelOrderByID_FullMethodName          = "/order_service.pkg.pb.OrderService/CancelOrderByID"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetOrderByIDWithItems(ctx context.Context, in *GetOrderByIDWithItemsRequest, opts ...grpc.CallOption) (*GetOrderByIDWithItemsResponse, error)
	GetOrderByIDOnly(ctx context.Context, in *GetOrderByIDOnlyRequest, opts ...grpc.CallOption) (*GetOrderByIDOnlyResponse, error)
	GetOrdersByBuyerIDStatus(ctx context.Context, in *GetOrdersByBuyerIDStatusRequest, opts ...grpc.CallOption) (*GetOrdersByBuyerIDStatusResponse, error)
	GetOrderItemsByOrderID(ctx context.Context, in *GetOrderItemsByOrderIDRequest, opts ...grpc.CallOption) (*GetOrderItemsByOrderIDResponse, error)
	UpdateOrderByID(ctx context.Context, in *UpdateOrderByIDRequest, opts ...grpc.CallOption) (*UpdateOrderByIDResponse, error)
	CancelOrderByID(ctx context.Context, in *CancelOrderByIDRequest, opts ...grpc.CallOption) (*CancelOrderByIDResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderByIDWithItems(ctx context.Context, in *GetOrderByIDWithItemsRequest, opts ...grpc.CallOption) (*GetOrderByIDWithItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderByIDWithItemsResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrderByIDWithItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderByIDOnly(ctx context.Context, in *GetOrderByIDOnlyRequest, opts ...grpc.CallOption) (*GetOrderByIDOnlyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderByIDOnlyResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrderByIDOnly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersByBuyerIDStatus(ctx context.Context, in *GetOrdersByBuyerIDStatusRequest, opts ...grpc.CallOption) (*GetOrdersByBuyerIDStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersByBuyerIDStatusResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrdersByBuyerIDStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderItemsByOrderID(ctx context.Context, in *GetOrderItemsByOrderIDRequest, opts ...grpc.CallOption) (*GetOrderItemsByOrderIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderItemsByOrderIDResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrderItemsByOrderID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrderByID(ctx context.Context, in *UpdateOrderByIDRequest, opts ...grpc.CallOption) (*UpdateOrderByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderByIDResponse)
	err := c.cc.Invoke(ctx, OrderService_UpdateOrderByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOrderByID(ctx context.Context, in *CancelOrderByIDRequest, opts ...grpc.CallOption) (*CancelOrderByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderByIDResponse)
	err := c.cc.Invoke(ctx, OrderService_CancelOrderByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrderByIDWithItems(context.Context, *GetOrderByIDWithItemsRequest) (*GetOrderByIDWithItemsResponse, error)
	GetOrderByIDOnly(context.Context, *GetOrderByIDOnlyRequest) (*GetOrderByIDOnlyResponse, error)
	GetOrdersByBuyerIDStatus(context.Context, *GetOrdersByBuyerIDStatusRequest) (*GetOrdersByBuyerIDStatusResponse, error)
	GetOrderItemsByOrderID(context.Context, *GetOrderItemsByOrderIDRequest) (*GetOrderItemsByOrderIDResponse, error)
	UpdateOrderByID(context.Context, *UpdateOrderByIDRequest) (*UpdateOrderByIDResponse, error)
	CancelOrderByID(context.Context, *CancelOrderByIDRequest) (*CancelOrderByIDResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderByIDWithItems(context.Context, *GetOrderByIDWithItemsRequest) (*GetOrderByIDWithItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByIDWithItems not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderByIDOnly(context.Context, *GetOrderByIDOnlyRequest) (*GetOrderByIDOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByIDOnly not implemented")
}
func (UnimplementedOrderServiceServer) GetOrdersByBuyerIDStatus(context.Context, *GetOrdersByBuyerIDStatusRequest) (*GetOrdersByBuyerIDStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByBuyerIDStatus not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderItemsByOrderID(context.Context, *GetOrderItemsByOrderIDRequest) (*GetOrderItemsByOrderIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderItemsByOrderID not implemented")
}
func (UnimplementedOrderServiceServer) UpdateOrderByID(context.Context, *UpdateOrderByIDRequest) (*UpdateOrderByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderByID not implemented")
}
func (UnimplementedOrderServiceServer) CancelOrderByID(context.Context, *CancelOrderByIDRequest) (*CancelOrderByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrderByID not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderByIDWithItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIDWithItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderByIDWithItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrderByIDWithItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderByIDWithItems(ctx, req.(*GetOrderByIDWithItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderByIDOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIDOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderByIDOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrderByIDOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderByIDOnly(ctx, req.(*GetOrderByIDOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersByBuyerIDStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByBuyerIDStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersByBuyerIDStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrdersByBuyerIDStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersByBuyerIDStatus(ctx, req.(*GetOrdersByBuyerIDStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderItemsByOrderID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderItemsByOrderIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderItemsByOrderID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrderItemsByOrderID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderItemsByOrderID(ctx, req.(*GetOrderItemsByOrderIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_UpdateOrderByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrderByID(ctx, req.(*UpdateOrderByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CancelOrderByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOrderByID(ctx, req.(*CancelOrderByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_service.pkg.pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrderByIDWithItems",
			Handler:    _OrderService_GetOrderByIDWithItems_Handler,
		},
		{
			MethodName: "GetOrderByIDOnly",
			Handler:    _OrderService_GetOrderByIDOnly_Handler,
		},
		{
			MethodName: "GetOrdersByBuyerIDStatus",
			Handler:    _OrderService_GetOrdersByBuyerIDStatus_Handler,
		},
		{
			MethodName: "GetOrderItemsByOrderID",
			Handler:    _OrderService_GetOrderItemsByOrderID_Handler,
		},
		{
			MethodName: "UpdateOrderByID",
			Handler:    _OrderService_UpdateOrderByID_Handler,
		},
		{
			MethodName: "CancelOrderByID",
			Handler:    _OrderService_CancelOrderByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
