services:
  redis:
    image: redis:8.2.1-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      test-network:
    volumes:
      - redis-data:/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

networks:
  test-network:

volumes:
  redis-data: