services:

#  etcd:
#    image: bitnami/etcd
#    networks:
#      - test-network
#    ports:
#      - "2379:2379"
#      - "2380:2380"
#    environment:
#      ALLOW_NONE_AUTHENTICATION: yes
#      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
#      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 3s
#        window: 30s
#
#  patroni-postgresql:
#    image: registry.opensource.zalan.do/acid/spilo-15
#    networks:
#      - test-network
#    ports:
#      - "5432:5432"
#    environment:
#      SCOPE: pg-cluster
#      PGUSER_SUPERUSER: admin
#      PGPASSWORD_SUPERUSER: admin
#      PGHOME: /home/postgres
#      ETCD3_HOST: etcd:2379
#    depends_on:
#      - etcd
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 3s
#        window: 30s

  redis-node-1:
#    image: redis:8.2.1-alpine
    image: redis_custom:latest
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
      - target: 16379
        published: 16380
        protocol: tcp
        mode: host
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip redis-node-1
      --appendonly yes
    networks:
      test-network:
#    volumes:
#      - redis-data-1:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        window: 10s
  redis-node-2:
    image: redis:8.2.1-alpine
    ports:
      - target: 6379
        published: 6381
        protocol: tcp
        mode: host
      - target: 16379
        published: 16381
        protocol: tcp
        mode: host
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip redis-node-2
      --appendonly yes
    networks:
      test-network:
#    volumes:
#      - redis-data-2:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        window: 10s
  redis-node-3:
    image: redis:8.2.1-alpine
    ports:
      - target: 6379
        published: 6382
        protocol: tcp
        mode: host
      - target: 16379
        published: 16382
        protocol: tcp
        mode: host
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip redis-node-3
      --appendonly yes
    networks:
      test-network:
#    volumes:
#      - redis-data-3:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        window: 10s
  redis-node-4:
    image: redis:8.2.1-alpine
    ports:
      - target: 6379
        published: 6383
        protocol: tcp
        mode: host
      - target: 16379
        published: 16383
        protocol: tcp
        mode: host
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip redis-node-4
      --appendonly yes
    networks:
      test-network:
#    volumes:
#      - redis-data-4:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        window: 10s
  redis-node-5:
    image: redis:8.2.1-alpine
    ports:
      - target: 6379
        published: 6384
        protocol: tcp
        mode: host
      - target: 16379
        published: 16384
        protocol: tcp
        mode: host
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip redis-node-5
      --appendonly yes
    networks:
      test-network:
#    volumes:
#      - redis-data-5:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        window: 10s
  redis-node-6:
    image: redis:8.2.1-alpine
    ports:
      - target: 6379
        published: 6385
        protocol: tcp
        mode: host
      - target: 16379
        published: 16385
        protocol: tcp
        mode: host
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip redis-node-6
      --appendonly yes
    networks:
      test-network:
#    volumes:
#      - redis-data-6:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        window: 10s



networks:
  test-network:
    driver: overlay

