// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: payment.proto

package paymentpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A payment covers a whole checkout (all orders of the checkout that await payment). The provider is a
// SIMULATION ("mockpay"): see .claude/docs/platform/04-orders-payments.md for the test cards.
//
// Statuses: REQUIRES_ACTION, PROCESSING, SUCCEEDED, FAILED, CANCELED, EXPIRED, PARTIALLY_REFUNDED, REFUNDED
type Attempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Scenario      string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"` // card_declined, insufficient_funds, requires_3ds, provider_error, timeout, success, ...
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`     // SUCCEEDED | FAILED | PENDING
	FailureCode   string                 `protobuf:"bytes,4,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	At            string                 `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attempt.ProtoReflect.Descriptor instead.
func (*Attempt) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Attempt) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Attempt) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Attempt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Attempt) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *Attempt) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

type Refund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     uint64                 `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // SUCCEEDED | FAILED
	RefundKey     string                 `protobuf:"bytes,7,opt,name=refund_key,json=refundKey,proto3" json:"refund_key,omitempty"`
	At            string                 `protobuf:"bytes,8,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *Refund) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Refund) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *Refund) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Refund) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Refund) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Refund) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Refund) GetRefundKey() string {
	if x != nil {
		return x.RefundKey
	}
	return ""
}

func (x *Refund) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CheckoutId    string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	BuyerId       uint64                 `protobuf:"varint,3,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,6,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Provider      string                 `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef   string                 `protobuf:"bytes,9,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`  // bank transfer content / reference shown to the buyer
	FailureCode   string                 `protobuf:"bytes,10,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"` // last failed attempt
	CardLast4     string                 `protobuf:"bytes,11,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PaidAt        string                 `protobuf:"bytes,13,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RefundedMinor int64                  `protobuf:"varint,15,opt,name=refunded_minor,json=refundedMinor,proto3" json:"refunded_minor,omitempty"`
	// what the buyer should do next: enter_card | otp | approve_in_wallet | transfer_and_confirm | wait | none
	NextAction    string     `protobuf:"bytes,16,opt,name=next_action,json=nextAction,proto3" json:"next_action,omitempty"`
	Attempts      []*Attempt `protobuf:"bytes,17,rep,name=attempts,proto3" json:"attempts,omitempty"` // admin view only
	Refunds       []*Refund  `protobuf:"bytes,18,rep,name=refunds,proto3" json:"refunds,omitempty"`   // admin view only
	OrderIds      []uint64   `protobuf:"varint,19,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *Payment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *Payment) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Payment) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *Payment) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *Payment) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *Payment) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Payment) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetRefundedMinor() int64 {
	if x != nil {
		return x.RefundedMinor
	}
	return 0
}

func (x *Payment) GetNextAction() string {
	if x != nil {
		return x.NextAction
	}
	return ""
}

func (x *Payment) GetAttempts() []*Attempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *Payment) GetRefunds() []*Refund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

func (x *Payment) GetOrderIds() []uint64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId       uint64                 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"` // buyer view: must own the payment
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPaymentRequest) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *GetPaymentRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type GetPaymentByCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutId    string                 `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	BuyerId       uint64                 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByCheckoutRequest) Reset() {
	*x = GetPaymentByCheckoutRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByCheckoutRequest) ProtoMessage() {}

func (x *GetPaymentByCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByCheckoutRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentByCheckoutRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *GetPaymentByCheckoutRequest) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *GetPaymentByCheckoutRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

// ConfirmPayment submits the buyer's action on the (simulated) payment page.
type ConfirmPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint64                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	BuyerId       uint64                 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"` // MOCK_CARD: only used to choose the simulated outcome, never stored (last 4 digits only)
	CardExp       string                 `protobuf:"bytes,4,opt,name=card_exp,json=cardExp,proto3" json:"card_exp,omitempty"`          // MM/YY
	CardCvc       string                 `protobuf:"bytes,5,opt,name=card_cvc,json=cardCvc,proto3" json:"card_cvc,omitempty"`
	Otp           string                 `protobuf:"bytes,6,opt,name=otp,proto3" json:"otp,omitempty"`          // 3-D Secure code
	Approve       bool                   `protobuf:"varint,7,opt,name=approve,proto3" json:"approve,omitempty"` // MOCK_WALLET / MOCK_BANK_TRANSFER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ConfirmPaymentRequest) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *ConfirmPaymentRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetCardExp() string {
	if x != nil {
		return x.CardExp
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetCardCvc() string {
	if x != nil {
		return x.CardCvc
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint64                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	BuyerId       uint64                 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *CancelPaymentRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CancelPaymentRequest) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *ListPaymentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListPaymentsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ListPaymentsRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint64                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,2,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *RefundPaymentRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *RefundPaymentRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ForceStatus is a development tool (ENV=dev only): apply a provider outcome right now.
type ForceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint64                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // SUCCEEDED | FAILED | EXPIRED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceStatusRequest) Reset() {
	*x = ForceStatusRequest{}
	mi := &file_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceStatusRequest) ProtoMessage() {}

func (x *ForceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceStatusRequest.ProtoReflect.Descriptor instead.
func (*ForceStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

func (x *ForceStatusRequest) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ForceStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\x16payment_service.pkg.pb\x1a\x1bbuf/validate/validate.proto\"\x80\x01\n" +
	"\aAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\ffailure_code\x18\x04 \x01(\tR\vfailureCode\x12\x0e\n" +
	"\x02at\x18\x05 \x01(\tR\x02at\"\xd4\x01\n" +
	"\x06Refund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\x04R\tpaymentId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"refund_key\x18\a \x01(\tR\trefundKey\x12\x0e\n" +
	"\x02at\x18\b \x01(\tR\x02at\"\xf8\x04\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x12\x19\n" +
	"\bbuyer_id\x18\x03 \x01(\x04R\abuyerId\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\famount_minor\x18\x06 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\t \x01(\tR\vproviderRef\x12!\n" +
	"\ffailure_code\x18\n" +
	" \x01(\tR\vfailureCode\x12\x1d\n" +
	"\n" +
	"card_last4\x18\v \x01(\tR\tcardLast4\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\tR\texpiresAt\x12\x17\n" +
	"\apaid_at\x18\r \x01(\tR\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12%\n" +
	"\x0erefunded_minor\x18\x0f \x01(\x03R\rrefundedMinor\x12\x1f\n" +
	"\vnext_action\x18\x10 \x01(\tR\n" +
	"nextAction\x12;\n" +
	"\battempts\x18\x11 \x03(\v2\x1f.payment_service.pkg.pb.AttemptR\battempts\x128\n" +
	"\arefunds\x18\x12 \x03(\v2\x1e.payment_service.pkg.pb.RefundR\arefunds\x12\x1b\n" +
	"\torder_ids\x18\x13 \x03(\x04R\borderIds\"Y\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x04R\abuyerId\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"t\n" +
	"\x1bGetPaymentByCheckoutRequest\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x04R\abuyerId\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"\xd4\x01\n" +
	"\x15ConfirmPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x04R\tpaymentId\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x04R\abuyerId\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x19\n" +
	"\bcard_exp\x18\x04 \x01(\tR\acardExp\x12\x19\n" +
	"\bcard_cvc\x18\x05 \x01(\tR\acardCvc\x12\x10\n" +
	"\x03otp\x18\x06 \x01(\tR\x03otp\x12\x18\n" +
	"\aapprove\x18\a \x01(\bR\aapprove\"P\n" +
	"\x14CancelPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x04R\tpaymentId\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x04R\abuyerId\"v\n" +
	"\x13ListPaymentsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x04R\bpageSize\"i\n" +
	"\x14ListPaymentsResponse\x12;\n" +
	"\bpayments\x18\x01 \x03(\v2\x1f.payment_service.pkg.pb.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"y\n" +
	"\x14RefundPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x04R\tpaymentId\x12*\n" +
	"\famount_minor\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\vamountMinor\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"K\n" +
	"\x12ForceStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x04R\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xc1\x05\n" +
	"\x0ePaymentService\x12X\n" +
	"\n" +
	"GetPayment\x12).payment_service.pkg.pb.GetPaymentRequest\x1a\x1f.payment_service.pkg.pb.Payment\x12l\n" +
	"\x14GetPaymentByCheckout\x123.payment_service.pkg.pb.GetPaymentByCheckoutRequest\x1a\x1f.payment_service.pkg.pb.Payment\x12`\n" +
	"\x0eConfirmPayment\x12-.payment_service.pkg.pb.ConfirmPaymentRequest\x1a\x1f.payment_service.pkg.pb.Payment\x12^\n" +
	"\rCancelPayment\x12,.payment_service.pkg.pb.CancelPaymentRequest\x1a\x1f.payment_service.pkg.pb.Payment\x12i\n" +
	"\fListPayments\x12+.payment_service.pkg.pb.ListPaymentsRequest\x1a,.payment_service.pkg.pb.ListPaymentsResponse\x12^\n" +
	"\rRefundPayment\x12,.payment_service.pkg.pb.RefundPaymentRequest\x1a\x1f.payment_service.pkg.pb.Payment\x12Z\n" +
	"\vForceStatus\x12*.payment_service.pkg.pb.ForceStatusRequest\x1a\x1f.payment_service.pkg.pb.PaymentB\x1bZ\x19payment-service/paymentpbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_payment_proto_goTypes = []any{
	(*Attempt)(nil),                     // 0: payment_service.pkg.pb.Attempt
	(*Refund)(nil),                      // 1: payment_service.pkg.pb.Refund
	(*Payment)(nil),                     // 2: payment_service.pkg.pb.Payment
	(*GetPaymentRequest)(nil),           // 3: payment_service.pkg.pb.GetPaymentRequest
	(*GetPaymentByCheckoutRequest)(nil), // 4: payment_service.pkg.pb.GetPaymentByCheckoutRequest
	(*ConfirmPaymentRequest)(nil),       // 5: payment_service.pkg.pb.ConfirmPaymentRequest
	(*CancelPaymentRequest)(nil),        // 6: payment_service.pkg.pb.CancelPaymentRequest
	(*ListPaymentsRequest)(nil),         // 7: payment_service.pkg.pb.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),        // 8: payment_service.pkg.pb.ListPaymentsResponse
	(*RefundPaymentRequest)(nil),        // 9: payment_service.pkg.pb.RefundPaymentRequest
	(*ForceStatusRequest)(nil),          // 10: payment_service.pkg.pb.ForceStatusRequest
}
var file_payment_proto_depIdxs = []int32{
	0,  // 0: payment_service.pkg.pb.Payment.attempts:type_name -> payment_service.pkg.pb.Attempt
	1,  // 1: payment_service.pkg.pb.Payment.refunds:type_name -> payment_service.pkg.pb.Refund
	2,  // 2: payment_service.pkg.pb.ListPaymentsResponse.payments:type_name -> payment_service.pkg.pb.Payment
	3,  // 3: payment_service.pkg.pb.PaymentService.GetPayment:input_type -> payment_service.pkg.pb.GetPaymentRequest
	4,  // 4: payment_service.pkg.pb.PaymentService.GetPaymentByCheckout:input_type -> payment_service.pkg.pb.GetPaymentByCheckoutRequest
	5,  // 5: payment_service.pkg.pb.PaymentService.ConfirmPayment:input_type -> payment_service.pkg.pb.ConfirmPaymentRequest
	6,  // 6: payment_service.pkg.pb.PaymentService.CancelPayment:input_type -> payment_service.pkg.pb.CancelPaymentRequest
	7,  // 7: payment_service.pkg.pb.PaymentService.ListPayments:input_type -> payment_service.pkg.pb.ListPaymentsRequest
	9,  // 8: payment_service.pkg.pb.PaymentService.RefundPayment:input_type -> payment_service.pkg.pb.RefundPaymentRequest
	10, // 9: payment_service.pkg.pb.PaymentService.ForceStatus:input_type -> payment_service.pkg.pb.ForceStatusRequest
	2,  // 10: payment_service.pkg.pb.PaymentService.GetPayment:output_type -> payment_service.pkg.pb.Payment
	2,  // 11: payment_service.pkg.pb.PaymentService.GetPaymentByCheckout:output_type -> payment_service.pkg.pb.Payment
	2,  // 12: payment_service.pkg.pb.PaymentService.ConfirmPayment:output_type -> payment_service.pkg.pb.Payment
	2,  // 13: payment_service.pkg.pb.PaymentService.CancelPayment:output_type -> payment_service.pkg.pb.Payment
	8,  // 14: payment_service.pkg.pb.PaymentService.ListPayments:output_type -> payment_service.pkg.pb.ListPaymentsResponse
	2,  // 15: payment_service.pkg.pb.PaymentService.RefundPayment:output_type -> payment_service.pkg.pb.Payment
	2,  // 16: payment_service.pkg.pb.PaymentService.ForceStatus:output_type -> payment_service.pkg.pb.Payment
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
