// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: order.proto

package orderpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId       uint64                 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	OrderItem     []*OrderItem           `protobuf:"bytes,5,rep,name=order_item,json=orderItem,proto3" json:"order_item,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetOrderItem() []*OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint64                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDResponse) Reset() {
	*x = GetOrderByIDResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDResponse) ProtoMessage() {}

func (x *GetOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOrderByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrderByIDResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrdersByBuyerIDStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerId       uint64                 `protobuf:"varint,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByBuyerIDStatusRequest) Reset() {
	*x = GetOrdersByBuyerIDStatusRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByBuyerIDStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByBuyerIDStatusRequest) ProtoMessage() {}

func (x *GetOrdersByBuyerIDStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByBuyerIDStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByBuyerIDStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrdersByBuyerIDStatusRequest) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *GetOrdersByBuyerIDStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOrdersByBuyerIDStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Order         []*Order               `protobuf:"bytes,3,rep,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByBuyerIDStatusResponse) Reset() {
	*x = GetOrdersByBuyerIDStatusResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByBuyerIDStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByBuyerIDStatusResponse) ProtoMessage() {}

func (x *GetOrdersByBuyerIDStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByBuyerIDStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByBuyerIDStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrdersByBuyerIDStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOrdersByBuyerIDStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrdersByBuyerIDStatusResponse) GetOrder() []*Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderItemsByOrderIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderItemsByOrderIDRequest) Reset() {
	*x = GetOrderItemsByOrderIDRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderItemsByOrderIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderItemsByOrderIDRequest) ProtoMessage() {}

func (x *GetOrderItemsByOrderIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderItemsByOrderIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderItemsByOrderIDRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderItemsByOrderIDRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderItemsByOrderIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	OrderItem     []*OrderItem           `protobuf:"bytes,3,rep,name=order_item,json=orderItem,proto3" json:"order_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderItemsByOrderIDResponse) Reset() {
	*x = GetOrderItemsByOrderIDResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderItemsByOrderIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderItemsByOrderIDResponse) ProtoMessage() {}

func (x *GetOrderItemsByOrderIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderItemsByOrderIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderItemsByOrderIDResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderItemsByOrderIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOrderItemsByOrderIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrderItemsByOrderIDResponse) GetOrderItem() []*OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type UpdateOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderByIDRequest) Reset() {
	*x = UpdateOrderByIDRequest{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderByIDRequest) ProtoMessage() {}

func (x *UpdateOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderByIDRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Massage       string                 `protobuf:"bytes,1,opt,name=massage,proto3" json:"massage,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderByIDResponse) Reset() {
	*x = UpdateOrderByIDResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderByIDResponse) ProtoMessage() {}

func (x *UpdateOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateOrderByIDResponse) GetMassage() string {
	if x != nil {
		return x.Massage
	}
	return ""
}

func (x *UpdateOrderByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderByIDRequest) Reset() {
	*x = CancelOrderByIDRequest{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderByIDRequest) ProtoMessage() {}

func (x *CancelOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *CancelOrderByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderByIDResponse) Reset() {
	*x = CancelOrderByIDResponse{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderByIDResponse) ProtoMessage() {}

func (x *CancelOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *CancelOrderByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelOrderByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x14order_service.pkg.pb\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x04R\abuyerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12>\n" +
	"\n" +
	"order_item\x18\x05 \x03(\v2\x1f.order_service.pkg.pb.OrderItemR\torderItem\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa9\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x04R\x02ID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"G\n" +
	"\x12CreateOrderRequest\x121\n" +
	"\x05order\x18\x01 \x01(\v2\x1b.order_service.pkg.pb.OrderR\x05order\"I\n" +
	"\x13CreateOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"%\n" +
	"\x13GetOrderByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"}\n" +
	"\x14GetOrderByIDResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x121\n" +
	"\x05order\x18\x03 \x01(\v2\x1b.order_service.pkg.pb.OrderR\x05order\"T\n" +
	"\x1fGetOrdersByBuyerIDStatusRequest\x12\x19\n" +
	"\bbuyer_id\x18\x01 \x01(\x04R\abuyerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x89\x01\n" +
	" GetOrdersByBuyerIDStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x121\n" +
	"\x05order\x18\x03 \x03(\v2\x1b.order_service.pkg.pb.OrderR\x05order\":\n" +
	"\x1dGetOrderItemsByOrderIDRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"\x94\x01\n" +
	"\x1eGetOrderItemsByOrderIDResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12>\n" +
	"\n" +
	"order_item\x18\x03 \x03(\v2\x1f.order_service.pkg.pb.OrderItemR\torderItem\"K\n" +
	"\x16UpdateOrderByIDRequest\x121\n" +
	"\x05order\x18\x01 \x01(\v2\x1b.order_service.pkg.pb.OrderR\x05order\"M\n" +
	"\x17UpdateOrderByIDResponse\x12\x18\n" +
	"\amassage\x18\x01 \x01(\tR\amassage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"(\n" +
	"\x16CancelOrderByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"M\n" +
	"\x17CancelOrderByIDResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xcb\x05\n" +
	"\fOrderService\x12b\n" +
	"\vCreateOrder\x12(.order_service.pkg.pb.CreateOrderRequest\x1a).order_service.pkg.pb.CreateOrderResponse\x12e\n" +
	"\fGetOrderByID\x12).order_service.pkg.pb.GetOrderByIDRequest\x1a*.order_service.pkg.pb.GetOrderByIDResponse\x12\x89\x01\n" +
	"\x18GetOrdersByBuyerIDStatus\x125.order_service.pkg.pb.GetOrdersByBuyerIDStatusRequest\x1a6.order_service.pkg.pb.GetOrdersByBuyerIDStatusResponse\x12\x83\x01\n" +
	"\x16GetOrderItemsByOrderID\x123.order_service.pkg.pb.GetOrderItemsByOrderIDRequest\x1a4.order_service.pkg.pb.GetOrderItemsByOrderIDResponse\x12n\n" +
	"\x0fUpdateOrderByID\x12,.order_service.pkg.pb.UpdateOrderByIDRequest\x1a-.order_service.pkg.pb.UpdateOrderByIDResponse\x12n\n" +
	"\x0fCancelOrderByID\x12,.order_service.pkg.pb.CancelOrderByIDRequest\x1a-.order_service.pkg.pb.CancelOrderByIDResponseB\x17Z\x15order-service/orderpbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_order_proto_goTypes = []any{
	(*Order)(nil),                            // 0: order_service.pkg.pb.Order
	(*OrderItem)(nil),                        // 1: order_service.pkg.pb.OrderItem
	(*CreateOrderRequest)(nil),               // 2: order_service.pkg.pb.CreateOrderRequest
	(*CreateOrderResponse)(nil),              // 3: order_service.pkg.pb.CreateOrderResponse
	(*GetOrderByIDRequest)(nil),              // 4: order_service.pkg.pb.GetOrderByIDRequest
	(*GetOrderByIDResponse)(nil),             // 5: order_service.pkg.pb.GetOrderByIDResponse
	(*GetOrdersByBuyerIDStatusRequest)(nil),  // 6: order_service.pkg.pb.GetOrdersByBuyerIDStatusRequest
	(*GetOrdersByBuyerIDStatusResponse)(nil), // 7: order_service.pkg.pb.GetOrdersByBuyerIDStatusResponse
	(*GetOrderItemsByOrderIDRequest)(nil),    // 8: order_service.pkg.pb.GetOrderItemsByOrderIDRequest
	(*GetOrderItemsByOrderIDResponse)(nil),   // 9: order_service.pkg.pb.GetOrderItemsByOrderIDResponse
	(*UpdateOrderByIDRequest)(nil),           // 10: order_service.pkg.pb.UpdateOrderByIDRequest
	(*UpdateOrderByIDResponse)(nil),          // 11: order_service.pkg.pb.UpdateOrderByIDResponse
	(*CancelOrderByIDRequest)(nil),           // 12: order_service.pkg.pb.CancelOrderByIDRequest
	(*CancelOrderByIDResponse)(nil),          // 13: order_service.pkg.pb.CancelOrderByIDResponse
	(*timestamppb.Timestamp)(nil),            // 14: google.protobuf.Timestamp
}
var file_order_proto_depIdxs = []int32{
	1,  // 0: order_service.pkg.pb.Order.order_item:type_name -> order_service.pkg.pb.OrderItem
	14, // 1: order_service.pkg.pb.Order.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: order_service.pkg.pb.Order.updated_at:type_name -> google.protobuf.Timestamp
	14, // 3: order_service.pkg.pb.OrderItem.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: order_service.pkg.pb.OrderItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: order_service.pkg.pb.CreateOrderRequest.order:type_name -> order_service.pkg.pb.Order
	0,  // 6: order_service.pkg.pb.GetOrderByIDResponse.order:type_name -> order_service.pkg.pb.Order
	0,  // 7: order_service.pkg.pb.GetOrdersByBuyerIDStatusResponse.order:type_name -> order_service.pkg.pb.Order
	1,  // 8: order_service.pkg.pb.GetOrderItemsByOrderIDResponse.order_item:type_name -> order_service.pkg.pb.OrderItem
	0,  // 9: order_service.pkg.pb.UpdateOrderByIDRequest.order:type_name -> order_service.pkg.pb.Order
	2,  // 10: order_service.pkg.pb.OrderService.CreateOrder:input_type -> order_service.pkg.pb.CreateOrderRequest
	4,  // 11: order_service.pkg.pb.OrderService.GetOrderByID:input_type -> order_service.pkg.pb.GetOrderByIDRequest
	6,  // 12: order_service.pkg.pb.OrderService.GetOrdersByBuyerIDStatus:input_type -> order_service.pkg.pb.GetOrdersByBuyerIDStatusRequest
	8,  // 13: order_service.pkg.pb.OrderService.GetOrderItemsByOrderID:input_type -> order_service.pkg.pb.GetOrderItemsByOrderIDRequest
	10, // 14: order_service.pkg.pb.OrderService.UpdateOrderByID:input_type -> order_service.pkg.pb.UpdateOrderByIDRequest
	12, // 15: order_service.pkg.pb.OrderService.CancelOrderByID:input_type -> order_service.pkg.pb.CancelOrderByIDRequest
	3,  // 16: order_service.pkg.pb.OrderService.CreateOrder:output_type -> order_service.pkg.pb.CreateOrderResponse
	5,  // 17: order_service.pkg.pb.OrderService.GetOrderByID:output_type -> order_service.pkg.pb.GetOrderByIDResponse
	7,  // 18: order_service.pkg.pb.OrderService.GetOrdersByBuyerIDStatus:output_type -> order_service.pkg.pb.GetOrdersByBuyerIDStatusResponse
	9,  // 19: order_service.pkg.pb.OrderService.GetOrderItemsByOrderID:output_type -> order_service.pkg.pb.GetOrderItemsByOrderIDResponse
	11, // 20: order_service.pkg.pb.OrderService.UpdateOrderByID:output_type -> order_service.pkg.pb.UpdateOrderByIDResponse
	13, // 21: order_service.pkg.pb.OrderService.CancelOrderByID:output_type -> order_service.pkg.pb.CancelOrderByIDResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
