// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: analytics.proto

package analyticspb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Clickstream event handed over by the gateway. Fields 16+ are attached by the GATEWAY from the JWT / request;
// the gateway never copies them from the client body.
type TrackEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TsClient         string                 `protobuf:"bytes,3,opt,name=ts_client,json=tsClient,proto3" json:"ts_client,omitempty"` // RFC 3339
	AnonymousId      string                 `protobuf:"bytes,4,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Surface          string                 `protobuf:"bytes,6,opt,name=surface,proto3" json:"surface,omitempty"`
	Path             string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Referrer         string                 `protobuf:"bytes,8,opt,name=referrer,proto3" json:"referrer,omitempty"`
	ProductId        uint64                 `protobuf:"varint,9,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Position         uint32                 `protobuf:"varint,10,opt,name=position,proto3" json:"position,omitempty"`
	PropsJson        string                 `protobuf:"bytes,11,opt,name=props_json,json=propsJson,proto3" json:"props_json,omitempty"` // JSON object, <= 2 KB
	DeviceType       string                 `protobuf:"bytes,12,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Os               string                 `protobuf:"bytes,13,opt,name=os,proto3" json:"os,omitempty"`
	AppVersion       string                 `protobuf:"bytes,14,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	AnalyticsConsent bool                   `protobuf:"varint,15,opt,name=analytics_consent,json=analyticsConsent,proto3" json:"analytics_consent,omitempty"`
	UserId           uint64                 `protobuf:"varint,16,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role             string                 `protobuf:"bytes,17,opt,name=role,proto3" json:"role,omitempty"`
	StoreId          uint64                 `protobuf:"varint,18,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	IpHash           string                 `protobuf:"bytes,19,opt,name=ip_hash,json=ipHash,proto3" json:"ip_hash,omitempty"`
	UaFamily         string                 `protobuf:"bytes,20,opt,name=ua_family,json=uaFamily,proto3" json:"ua_family,omitempty"`
	Country          string                 `protobuf:"bytes,21,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackEvent) Reset() {
	*x = TrackEvent{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEvent) ProtoMessage() {}

func (x *TrackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEvent.ProtoReflect.Descriptor instead.
func (*TrackEvent) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TrackEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TrackEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackEvent) GetTsClient() string {
	if x != nil {
		return x.TsClient
	}
	return ""
}

func (x *TrackEvent) GetAnonymousId() string {
	if x != nil {
		return x.AnonymousId
	}
	return ""
}

func (x *TrackEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TrackEvent) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *TrackEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TrackEvent) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *TrackEvent) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *TrackEvent) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *TrackEvent) GetPropsJson() string {
	if x != nil {
		return x.PropsJson
	}
	return ""
}

func (x *TrackEvent) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *TrackEvent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *TrackEvent) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *TrackEvent) GetAnalyticsConsent() bool {
	if x != nil {
		return x.AnalyticsConsent
	}
	return false
}

func (x *TrackEvent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TrackEvent) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *TrackEvent) GetIpHash() string {
	if x != nil {
		return x.IpHash
	}
	return ""
}

func (x *TrackEvent) GetUaFamily() string {
	if x != nil {
		return x.UaFamily
	}
	return ""
}

func (x *TrackEvent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type IngestEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TrackEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventsRequest) Reset() {
	*x = IngestEventsRequest{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventsRequest) ProtoMessage() {}

func (x *IngestEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventsRequest.ProtoReflect.Descriptor instead.
func (*IngestEventsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEventsRequest) GetEvents() []*TrackEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type IngestEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Reasons       []string               `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"` // one entry per rejected event ("<index>:<reason>")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventsResponse) Reset() {
	*x = IngestEventsResponse{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventsResponse) ProtoMessage() {}

func (x *IngestEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventsResponse.ProtoReflect.Descriptor instead.
func (*IngestEventsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *IngestEventsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestEventsResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestEventsResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

// Whom a report is for. Set by the gateway from the JWT, never from the client.
type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`                       // "admin" = whole platform, "seller" = one store
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"` // required for seller
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *Scope) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Scope) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// summary | timeseries | top_products | funnel | low_stock | traffic | payments | search_terms | data_health
	Report        string `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Scope         *Scope `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	From          string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`               // RFC 3339; default now-30d
	To            string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`                   // RFC 3339; default now
	Granularity   string `protobuf:"bytes,5,opt,name=granularity,proto3" json:"granularity,omitempty"` // hour | day | week | month (timeseries, traffic); default day
	Sort          string `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`               // top_products: revenue | units | views | conversion | viewed_unsold
	Limit         int32  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

func (x *QueryRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *QueryRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *QueryRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *QueryRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *QueryRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsOf          string                 `protobuf:"bytes,1,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"` // RFC 3339 time the numbers were computed
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`         // "clickhouse"
	Cached        bool                   `protobuf:"varint,3,opt,name=cached,proto3" json:"cached,omitempty"`
	DataJson      string                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // the report payload (JSON), shape per report in docs/platform/06-api-contracts.md
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

func (x *QueryResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *QueryResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\x18analytics_service.pkg.pb\x1a\x1bbuf/validate/validate.proto\"\xe0\x04\n" +
	"\n" +
	"TrackEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tts_client\x18\x03 \x01(\tR\btsClient\x12!\n" +
	"\fanonymous_id\x18\x04 \x01(\tR\vanonymousId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x18\n" +
	"\asurface\x18\x06 \x01(\tR\asurface\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x1a\n" +
	"\breferrer\x18\b \x01(\tR\breferrer\x12\x1d\n" +
	"\n" +
	"product_id\x18\t \x01(\x04R\tproductId\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\rR\bposition\x12\x1d\n" +
	"\n" +
	"props_json\x18\v \x01(\tR\tpropsJson\x12\x1f\n" +
	"\vdevice_type\x18\f \x01(\tR\n" +
	"deviceType\x12\x0e\n" +
	"\x02os\x18\r \x01(\tR\x02os\x12\x1f\n" +
	"\vapp_version\x18\x0e \x01(\tR\n" +
	"appVersion\x12+\n" +
	"\x11analytics_consent\x18\x0f \x01(\bR\x10analyticsConsent\x12\x17\n" +
	"\auser_id\x18\x10 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04role\x18\x11 \x01(\tR\x04role\x12\x19\n" +
	"\bstore_id\x18\x12 \x01(\x04R\astoreId\x12\x17\n" +
	"\aip_hash\x18\x13 \x01(\tR\x06ipHash\x12\x1b\n" +
	"\tua_family\x18\x14 \x01(\tR\buaFamily\x12\x18\n" +
	"\acountry\x18\x15 \x01(\tR\acountry\"]\n" +
	"\x13IngestEventsRequest\x12F\n" +
	"\x06events\x18\x01 \x03(\v2$.analytics_service.pkg.pb.TrackEventB\b\xbaH\x05\x92\x01\x02\x102R\x06events\"h\n" +
	"\x14IngestEventsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x05R\brejected\x12\x18\n" +
	"\areasons\x18\x03 \x03(\tR\areasons\"6\n" +
	"\x05Scope\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\"\xd6\x01\n" +
	"\fQueryRequest\x12\x1f\n" +
	"\x06report\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06report\x125\n" +
	"\x05scope\x18\x02 \x01(\v2\x1f.analytics_service.pkg.pb.ScopeR\x05scope\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12 \n" +
	"\vgranularity\x18\x05 \x01(\tR\vgranularity\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\tR\x04sort\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"q\n" +
	"\rQueryResponse\x12\x13\n" +
	"\x05as_of\x18\x01 \x01(\tR\x04asOf\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06cached\x18\x03 \x01(\bR\x06cached\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\tR\bdataJson2\xdb\x01\n" +
	"\x10AnalyticsService\x12m\n" +
	"\fIngestEvents\x12-.analytics_service.pkg.pb.IngestEventsRequest\x1a..analytics_service.pkg.pb.IngestEventsResponse\x12X\n" +
	"\x05Query\x12&.analytics_service.pkg.pb.QueryRequest\x1a'.analytics_service.pkg.pb.QueryResponseB\x1fZ\x1danalytics-service/analyticspbb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_analytics_proto_goTypes = []any{
	(*TrackEvent)(nil),           // 0: analytics_service.pkg.pb.TrackEvent
	(*IngestEventsRequest)(nil),  // 1: analytics_service.pkg.pb.IngestEventsRequest
	(*IngestEventsResponse)(nil), // 2: analytics_service.pkg.pb.IngestEventsResponse
	(*Scope)(nil),                // 3: analytics_service.pkg.pb.Scope
	(*QueryRequest)(nil),         // 4: analytics_service.pkg.pb.QueryRequest
	(*QueryResponse)(nil),        // 5: analytics_service.pkg.pb.QueryResponse
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: analytics_service.pkg.pb.IngestEventsRequest.events:type_name -> analytics_service.pkg.pb.TrackEvent
	3, // 1: analytics_service.pkg.pb.QueryRequest.scope:type_name -> analytics_service.pkg.pb.Scope
	1, // 2: analytics_service.pkg.pb.AnalyticsService.IngestEvents:input_type -> analytics_service.pkg.pb.IngestEventsRequest
	4, // 3: analytics_service.pkg.pb.AnalyticsService.Query:input_type -> analytics_service.pkg.pb.QueryRequest
	2, // 4: analytics_service.pkg.pb.AnalyticsService.IngestEvents:output_type -> analytics_service.pkg.pb.IngestEventsResponse
	5, // 5: analytics_service.pkg.pb.AnalyticsService.Query:output_type -> analytics_service.pkg.pb.QueryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
